import { createIcon, type IconProps } from './factory';

export const IconEvent = (props: IconProps) => createIcon('event', props);
export const IconReceipt = (props: IconProps) => createIcon('receipt_long', props);
export const IconPersonAdd = (props: IconProps) => createIcon('person_add', props);
export const IconDataObject = (props: IconProps) => createIcon('data_object', props);
export const IconMoreVert = (props: IconProps) => createIcon('more_vert', props);
export const IconArrowBack = (props: IconProps) => createIcon('arrow_back', props);
export const IconCurrencyRupee = (props: IconProps) => createIcon('currency_rupee', props);
export const IconAdd_2 = (props: IconProps) => createIcon('add_2', props);
export const IconLogout = (props: IconProps) => createIcon('logout', props);
export const IconNote = (props: IconProps) => createIcon('note', props);
export const IconWarning = (props: IconProps) => createIcon('warning', props);
export const IconPayments = (props: IconProps) => createIcon('payments', props);
export const IconUniversalCurrencyAlt = (props: IconProps) => createIcon('universal_currency_alt', props);
export const IconMoneyBag = (props: IconProps) => createIcon('money_bag', props);
export const IconWifi = (props: IconProps) => createIcon('wifi', props);
export const IconLightbulb = (props: IconProps) => createIcon('lightbulb', props);
export const IconCheck = (props: IconProps) => createIcon('check', props);
export const IconCheckAlert = (props: IconProps) => createIcon('check_alert', props);
export const IconPriorityHigh = (props: IconProps) => createIcon('priority_high', props);
export const IconPersonAlert = (props: IconProps) => createIcon('person_alert', props);
export const IconPersonCheck = (props: IconProps) => createIcon('person_check', props);
export const IconPersonRemove = (props: IconProps) => createIcon('person_remove', props);
export const IconCall = (props: IconProps) => createIcon('call', props);
export const IconDelete = (props: IconProps) => createIcon('delete', props);
export const IconKingBed = (props: IconProps) => createIcon('king_bed', props);
export const IconEdit = (props: IconProps) => createIcon('edit', props);
export const IconInfo = (props: IconProps) => createIcon('info', props);
export const IconShare = (props: IconProps) => createIcon('share', props);
export const IconUndo = (props: IconProps) => createIcon('undo', props);
export const IconHistory = (props: IconProps) => createIcon('history', props);
export const IconFilterList = (props: IconProps) => createIcon('filter_list', props);
export const IconSearch = (props: IconProps) => createIcon('search', props);
export const IconError = (props: IconProps) => createIcon('error', props);
export const IconPerson = (props: IconProps) => createIcon('person', props);
export const IconEditOff = (props: IconProps) => createIcon('edit_off', props);
export const IconClose = (props: IconProps) => createIcon('close', props);
export const IconPersonEdit = (props: IconProps) => createIcon('person_edit', props);

export { IconWhatsApp } from './IconWhatsApp';
export { IconFirebase } from './IconFirebase';
export { IconGoogle } from './IconGoogle';
